name: simple_sneaker_shop
description: A simple Flutter app that shows a list of sneakers.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^1.1.0
  intl: ^0.17.0
  riverpod: ^1.0.3
  uuid: ^3.0.5


dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  mocktail: ^0.2.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
